# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from icasdk.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    ANALYSIS_STORAGE = "Analysis Storage"
    BUNDLE = "Bundle"
    BUNDLE_DATA = "Bundle Data"
    BUNDLE_PIPELINE = "Bundle Pipeline"
    BUNDLE_SAMPLE = "Bundle Sample"
    BUNDLE_TOOL = "Bundle Tool"
    CONNECTOR = "Connector"
    DATA = "Data"
    DATA_FORMAT = "Data Format"
    ENTITLED_BUNDLE = "Entitled Bundle"
    ENTITLEMENT_DETAIL = "Entitlement Detail"
    EVENT_CODE = "Event Code"
    EVENT_LOG = "Event Log"
    JOB = "Job"
    METADATA_MODEL = "Metadata Model"
    NOTIFICATION_CHANNEL = "Notification Channel"
    PIPELINE = "Pipeline"
    PIPELINE_LANGUAGE = "Pipeline Language"
    PROJECT = "Project"
    PROJECT_ANALYSIS = "Project Analysis"
    PROJECT_ANALYSIS_CREATION_BATCH = "Project Analysis Creation Batch"
    PROJECT_BASE = "Project Base"
    PROJECT_CUSTOM_EVENTS = "Project Custom Events"
    PROJECT_CUSTOM_NOTIFICATION_SUBSCRIPTIONS = "Project Custom Notification Subscriptions"
    PROJECT_DATA = "Project Data"
    PROJECT_DATA_LINKING_BATCH = "Project Data Linking Batch"
    PROJECT_DATA_TRANSFER = "Project Data Transfer"
    PROJECT_DATA_UPDATE_BATCH = "Project Data Update Batch"
    PROJECT_NOTIFICATION_SUBSCRIPTIONS = "Project Notification Subscriptions"
    PROJECT_PERMISSION = "Project Permission"
    PROJECT_PIPELINE = "Project Pipeline"
    PROJECT_SAMPLE = "Project Sample"
    PROJECT_SAMPLE_BATCH = "Project Sample Batch"
    REFERENCE_SET = "Reference Set"
    REGION = "Region"
    SAMPLE = "Sample"
    SEQUENCING_RUN = "Sequencing Run"
    STORAGE_BUNDLE = "Storage Bundle"
    STORAGE_CONFIGURATION = "Storage Configuration"
    STORAGE_CREDENTIALS = "Storage Credentials"
    SYSTEM = "System"
    TOKEN = "Token"
    USER = "User"
    WORKGROUP = "Workgroup"
