# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import icasdk
from icasdk.paths.api_bundles_bundle_id_tools_eligible_for_linking import get  # noqa: E501
from icasdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiBundlesBundleIdToolsEligibleForLinking(ApiTestMixin, unittest.TestCase):
    """
    ApiBundlesBundleIdToolsEligibleForLinking unit test stubs
        Retrieve a list of tools eligible for linking to the bundle.  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
