# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import icasdk
from icasdk.paths.api_bundles_bundle_id_samples_sample_id import delete  # noqa: E501
from icasdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiBundlesBundleIdSamplesSampleId(ApiTestMixin, unittest.TestCase):
    """
    ApiBundlesBundleIdSamplesSampleId unit test stubs
        Unlink a sample from a bundle.  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = delete.ApiFordelete(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204




if __name__ == '__main__':
    unittest.main()
